---
apiVersion: v1
kind: Namespace
metadata:
  name: deepfence
---
apiVersion: v1
kind: Secret
metadata:
  name: deepfence-docker-secret
  namespace: deepfence
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: deepfence-key
  namespace: deepfence
type: Opaque
data:
  deepfence-key: ""
---